version: "3"

tasks:
  build:
    desc: Build the application
    deps: [fmt]
    cmds:
      - go build -o bin/chess ./cmd

  run:
    desc: Run the application
    cmds:
      - go run ./cmd

  test:
    desc: Run tests
    cmds:
      - go test ./...

  test-verbose:
    desc: Run tests with verbose output
    cmds:
      - go test -v ./...

  lint:
    desc: Run linter and fix issues
    deps: [fmt]
    cmds:
      - golangci-lint run --fix

  fmt:
    desc: Format code
    cmds:
      - golines -w .
      - go fmt ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/

  dev:
    desc: Run in development mode (with file watching)
    deps: [build]
    cmds:
      - ./bin/chess
    sources:
      - "**/*.go"
    generates:
      - bin/chess
